# Generated by Django 4.0.3 on 2023-02-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEDxApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='lname',
            field=models.CharField(max_length=50),
        ),
    ]
