# Generated by Django 4.0.3 on 2023-02-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEDxApp', '0003_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat',
            new_name='assigned_to',
        ),
    ]
