# Generated by Django 4.0.3 on 2023-02-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEDxApp', '0005_attendee_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='id',
        ),
        migrations.AddField(
            model_name='seat',
            name='order',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
