# Generated by Django 4.0.3 on 2023-04-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEDxApp', '0007_rename_fname_attendee_name_remove_attendee_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='attendee',
            name='city',
            field=models.CharField(choices=[('riyadh', 'riyadh'), ('dammam', 'dammam'), ('jeddah', 'jeddah'), ('other', 'other')], default='riyadh', max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='education',
            field=models.CharField(choices=[('high_school', 'high_school'), ('university', 'university'), ('employed', 'employed')], default='high_school', max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='phone',
            field=models.IntegerField(default=1),
        ),
    ]
