# Generated by Django 4.0.3 on 2023-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEDxApp', '0009_alter_attendee_city_alter_attendee_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
