# Generated by Django 4.0.3 on 2023-04-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEDxApp', '0010_alter_attendee_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='city',
        ),
        migrations.AddField(
            model_name='attendee',
            name='country',
            field=models.CharField(choices=[('saudi', 'saudi'), ('kuwait', 'kuwait'), ('bahrain', 'bahrain'), ('uae', 'uae'), ('iraq', 'iraq'), ('syria', 'syria'), ('egypt', 'egypt'), ('oman', 'oman'), ('jordan', 'jordan'), ('morocco', 'morocco'), ('tunisia', 'tunisia'), ('sudan', 'sudan'), ('yemen', 'yemen'), ('other', 'other')], default='saudi', max_length=50),
            preserve_default=False,
        ),
    ]
