# Generated by Django 4.2 on 2023-04-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEDxApp', '0012_alter_attendee_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='education',
            field=models.CharField(choices=[('high_school', 'high_school'), ('university', 'university'), ('bachelors', 'bachelors'), ('masters', 'masters'), ('doctorate', 'doctorate'), ('other', 'other')], max_length=50),
        ),
    ]
